name: ci

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          scope: '@moonwalker'

      - run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: yarn lint

  publish:
    needs:
      - lint

    if: contains(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          scope: '@moonwalker'

      - run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
